/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicYtResolveRouteImport } from './routes/api/public/yt-resolve'
import { Route as ApiPublicYtProxyRouteImport } from './routes/api/public/yt-proxy'
import { Route as ApiPublicPaddleWebhookRouteImport } from './routes/api/public/paddle-webhook'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYtResolveRoute = ApiPublicYtResolveRouteImport.update({
  id: '/api/public/yt-resolve',
  path: '/api/public/yt-resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYtProxyRoute = ApiPublicYtProxyRouteImport.update({
  id: '/api/public/yt-proxy',
  path: '/api/public/yt-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaddleWebhookRoute = ApiPublicPaddleWebhookRouteImport.update({
  id: '/api/public/paddle-webhook',
  path: '/api/public/paddle-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/history': typeof HistoryRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/api/public/yt-proxy': typeof ApiPublicYtProxyRoute
  '/api/public/yt-resolve': typeof ApiPublicYtResolveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/history': typeof HistoryRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/api/public/yt-proxy': typeof ApiPublicYtProxyRoute
  '/api/public/yt-resolve': typeof ApiPublicYtResolveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/history': typeof HistoryRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/api/public/yt-proxy': typeof ApiPublicYtProxyRoute
  '/api/public/yt-resolve': typeof ApiPublicYtResolveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/billing'
    | '/history'
    | '/api/public/paddle-webhook'
    | '/api/public/yt-proxy'
    | '/api/public/yt-resolve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/billing'
    | '/history'
    | '/api/public/paddle-webhook'
    | '/api/public/yt-proxy'
    | '/api/public/yt-resolve'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/billing'
    | '/history'
    | '/api/public/paddle-webhook'
    | '/api/public/yt-proxy'
    | '/api/public/yt-resolve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  HistoryRoute: typeof HistoryRoute
  ApiPublicPaddleWebhookRoute: typeof ApiPublicPaddleWebhookRoute
  ApiPublicYtProxyRoute: typeof ApiPublicYtProxyRoute
  ApiPublicYtResolveRoute: typeof ApiPublicYtResolveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/yt-resolve': {
      id: '/api/public/yt-resolve'
      path: '/api/public/yt-resolve'
      fullPath: '/api/public/yt-resolve'
      preLoaderRoute: typeof ApiPublicYtResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/yt-proxy': {
      id: '/api/public/yt-proxy'
      path: '/api/public/yt-proxy'
      fullPath: '/api/public/yt-proxy'
      preLoaderRoute: typeof ApiPublicYtProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paddle-webhook': {
      id: '/api/public/paddle-webhook'
      path: '/api/public/paddle-webhook'
      fullPath: '/api/public/paddle-webhook'
      preLoaderRoute: typeof ApiPublicPaddleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  HistoryRoute: HistoryRoute,
  ApiPublicPaddleWebhookRoute: ApiPublicPaddleWebhookRoute,
  ApiPublicYtProxyRoute: ApiPublicYtProxyRoute,
  ApiPublicYtResolveRoute: ApiPublicYtResolveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
